service: book-data-pipeline

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'ap-northeast-2'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  handler:
    timeout: 60
      # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: img
    events:
    - schedule:
      rate: rate(10 minutes)
      input:
       category: '소설'
       stageParams:
        stage: dev
      inputPath: '$.stageVariables'
      inputTransformer:
        inputPathsMap:
          eventTime: '$.time'
        inputTemplate: '{"time": <eventTime>, "category": "value1"}'

