version: "3.3"
services:
  spark-master:
    image: book-data-pipeline-spark:0.1.0
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ../src:/opt/spark-apps/src
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    env_file:
      - ../.env.transform

  spark-worker-a:
    image: book-data-pipeline-spark:0.1.0
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    env_file:
      - ../.env.transform
    volumes:
       - ../src:/opt/spark-apps/src
       - ./data:/opt/spark-data

  spark-worker-b:
    image: book-data-pipeline-spark:0.1.0
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    env_file:
      - ../.env.transform
    volumes:
        - ../src:/opt/spark-apps/src
        - ./data:/opt/spark-data

  db:
    image: postgres
    environment:
      POSTGRES_DB: bookDB
      POSTGRES_USER: ${DB_USER}  # docker-compose --env-file .env.transform up -d
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
