version: "3.3"
services:
  spark-master:
    image: book-data-pipeline-spark:0.1.1
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ../src:/opt/spark-apps/src
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    env_file:
      - ../.env.transform

  spark-worker-a:
    image: book-data-pipeline-spark:0.1.1
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
      - postgreDB
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    env_file:
      - ../.env.transform
    volumes:
       - ../src:/opt/spark-apps/src
       - ./data:/opt/spark-data

  spark-worker-b:
    image: book-data-pipeline-spark:0.1.1
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
      - postgreDB
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    env_file:
      - ../.env.transform
    volumes:
        - ../src:/opt/spark-apps/src
        - ./data:/opt/spark-data

  postgreDB:
    image: postgres:latest
    ports:
      - "5431:5432"
    env_file:
      - ../.env.transform
    volumes:
      - ./data/data:/var/lib/postgresql/data
    restart: always

